name             'virtual-hosts'
maintainer       'Tomas Susanka'
maintainer_email 'susantom@fit.cvut.cz'
license          'MIT'
description      'Adds Apache domain configuration for sites'
version          '0.1.2'
